"""add suppression and new models

Revision ID: 28f5a88dd0de
Revises: 0001_init
Create Date: 2025-11-24 21:44:20.928427
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '28f5a88dd0de'
down_revision = '0001_init'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suppressed_emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppressed_emails_email'), 'suppressed_emails', ['email'], unique=False)
    op.create_index(op.f('ix_suppressed_emails_tenant_id'), 'suppressed_emails', ['tenant_id'], unique=False)
    op.drop_index('ix_campaigns_id', table_name='campaigns')
    op.drop_index('ix_email_logs_id', table_name='email_logs')
    op.drop_index('ix_subscribers_id', table_name='subscribers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_subscribers_id', 'subscribers', ['id'], unique=False)
    op.create_index('ix_email_logs_id', 'email_logs', ['id'], unique=False)
    op.create_index('ix_campaigns_id', 'campaigns', ['id'], unique=False)
    op.drop_index(op.f('ix_suppressed_emails_tenant_id'), table_name='suppressed_emails')
    op.drop_index(op.f('ix_suppressed_emails_email'), table_name='suppressed_emails')
    op.drop_table('suppressed_emails')
    # ### end Alembic commands ###
