"""add suppression and new models

Revision ID: c30dd1f959ec
Revises: 28f5a88dd0de
Create Date: 2025-11-24 21:45:34.192479
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'c30dd1f959ec'
down_revision = '28f5a88dd0de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
